spring:
  application:
    name: ms-books-catalogue

opensearch:
  host: ${OPENSEARCH_HOST:luminous-hornbeam-1mfw0psh.us-east-1.bonsaisearch.net}
  port: ${OPENSEARCH_PORT:443}
  scheme: ${OPENSEARCH_SCHEME:https}
  username: ${OPENSEARCH_USERNAME:b05a4fcbbd}
  password: ${OPENSEARCH_PASSWORD:57bbd5b5eb4a3b2542d6}
  index: ${OPENSEARCH_INDEX:books}

server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%-15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    root: WARN
    com.relatosDePapel: INFO
    org.springframework.web: WARN
    org.springframework.cloud.netflix.eureka: WARN
    com.netflix.discovery: WARN
